CREATE TABLE "automation_score" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "automation_score_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"task_id" integer NOT NULL,
	"score_pct" numeric(5, 2) DEFAULT '0' NOT NULL,
	"horizon" varchar(10) DEFAULT 'now' NOT NULL,
	"source" varchar(20) DEFAULT 'default',
	"analysis" text,
	"reasoning" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "occupation" (
	"code_rome" varchar(10) PRIMARY KEY NOT NULL,
	"titre" varchar(255) NOT NULL,
	"secteur" varchar(100),
	"description" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "task" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "task_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"occupation_code_rome" varchar(10) NOT NULL,
	"libelle" varchar(255) NOT NULL,
	"description" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "user_profile" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_profile_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"email" varchar(255) NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "user_profile_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "user_simulation" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_simulation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer,
	"occupation_code_rome" varchar(10) NOT NULL,
	"json_temps_par_tache" text NOT NULL,
	"score_global" numeric(5, 2) DEFAULT '0' NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "automation_score" ADD CONSTRAINT "automation_score_task_id_task_id_fk" FOREIGN KEY ("task_id") REFERENCES "public"."task"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "task" ADD CONSTRAINT "task_occupation_code_rome_occupation_code_rome_fk" FOREIGN KEY ("occupation_code_rome") REFERENCES "public"."occupation"("code_rome") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_simulation" ADD CONSTRAINT "user_simulation_user_id_user_profile_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user_profile"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_simulation" ADD CONSTRAINT "user_simulation_occupation_code_rome_occupation_code_rome_fk" FOREIGN KEY ("occupation_code_rome") REFERENCES "public"."occupation"("code_rome") ON DELETE no action ON UPDATE no action;